### ISSUE TITLE
Button trigger don't work in mecury - it is possible :)?

### ISSUE THREAD

**Issue by kamiljaszczynski** [mljar/mercury#145]
Hello,

I have code like this:
```
import ipywidgets as widgets
from IPython.display import display
output = widgets.Output()

@output.capture(clear_output=False,wait=True) # based on https://github.com/jupyter-widgets/ipywidgets/issues/1846 and https://ipywidgets.readthedocs.io/en/latest/examples/Output%20Widget.html
def sayHello(b):
    print("You have pushed the button, congratulations I guess.")
    run_button.description = "pressed..."

run_button = widgets.Button(
    description = 'continue'
)
print("Hello, please push the continue button")
run_button.on_click(sayHello)
display(run_button)
output
```

Normal in Jupyter Notebook Server work fine and button description changed to pressed.
When i run this on Mercury there is no efect. 

I need read some lines from file ( tweets ) or from DB. Then Person should see that tweet and answer that is fake or not fake. 
So i need some interaction with user. It is posible using Mercury :)?

Thanks

**Comment by pplonski** [comment]
Hi @kamiljaszczynski,

The ipywidgets will not work with Mercury. The ipywidgets package requires running kernel. The Mercury collects the widget's input and executes the full notebook.

In Mercury, you should define widgets in the YAML header, here is an example of YAML

```yaml
title: Analyze tweets
description: Is this tweet fake or not?
params:
    answer:
        input: select
        label: Is it fake?
        choices: [fake, not fake, hard to say]
        value: hard to say
```

The widgets [docs](https://mercury-docs.readthedocs.io/en/latest/widgets/). Do you need help with creating the first app in Mercury? I can help you if your notebook is public.
