### ISSUE TITLE
mercury run only seems to run the mercury demo app

### ISSUE THREAD

**Issue by traderjoemama** [mljar/mercury#200]
Hello,

I have a typical Python project with some Jupyter notebooks. I added a new notebook `mynotebook.ipynb` in the same location as my others, then proceeded to replicate the "getting started" app in that new notebook, per instructions here: https://mercury-docs.readthedocs.io/en/latest/get-started/.

Attempting to run this "getting started" app, and in my terminal, I navigated to the location of `mynotebook.ipynb` then executed: `mercury run mynotebook.ipynb`. It starts.

Then, when opening my browser to `http://127.0.0.1:8000/`, unfortunately, I can only see the demo that's normally viewed via `mercury run demo`. And, indeed, the terminal shows that the built-in demo notebook is being served: `"GET /media/demo-notebook.html HTTP/1.1" 304 0` and not my `mynotebook.ipynb` app.

How can I get `mercury run mynotebook.ipynb` to run my app? 

FWIW, yes, the raw YAML config is in the `mynotebook.ipynb` notebook:

```
---
title: Hello
description: Hello App
params:
    planet:
        input: select
        label: Please select a planet
        value: Earth
        choices: [Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune ]
---
```

Thank you!
