### ISSUE TITLE
Add option to create files for download

### ISSUE THREAD

**Issue by pplonski** [mljar/mercury#37]
Please add feature to create a directory that will allow to download all files from it.

Example:

```yaml
title: My app
description: App with file download
params:
    output_dir:
        output: dir
```
```py
# %% next cell
output_dir = "output/directory/path"

# %% next cell
import os
with open(os.path.join(output_dir, "my_file.txt"), "w") as fout:
    fout.write("This is a test")
```

In the above example the file `my_file.txt` should be available to download in the Mercury app.  Different users should have different output folders.
