### ISSUE TITLE
add validation for params

### ISSUE THREAD

**Issue by pplonski** [mljar/mercury#69]
When initializing the notebook please check if params are correct. For example the below YAML should not be parsed because `choices` should be a list. There should be some warning/error message.

```
---
title: Hello 🌍🪐
description: Hello app
params:
    planet:
        input: select
        label: Please select a planet
        value: Earth
        choices: Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune
---
```

The correct YAML:
```
---
title: Hello 🌍🪐
description: Hello app
params:
    planet:
        input: select
        label: Please select a planet
        value: Earth
        choices: [Mercury, Venus, Earth, Mars, Jupiter, Saturn, Uranus, Neptune]
---
```
