### ISSUE TITLE
Text widgets allow multi-line texts, but if you add a text with line feeds (enter), it breaks the app.

### ISSUE THREAD

**Issue by bicubico** [mljar/mercury#76]
```
params:
    description:
        input: text
        label: Multi - line text
        value: Single line text
        rows: 5
```

![issue-mercury](https://user-images.githubusercontent.com/5770504/160408258-0ea994e7-3e8b-4ecc-8030-5d3731967fa3.png)
