### ISSUE TITLE
add option to add just label without widget in the sidebar

### ISSUE THREAD

**Issue by pplonski** [mljar/mercury#87]
Please add option to add just label without widget in the sidebar

**Comment by pplonski** [comment]
You can add Markdown text in the sidebar. Example YAML

```yaml
---
title: 🚀 Demo notebook
description: Simple notebook with widgets demo
show-code: True
params:
    year:
        input: slider
        label: Please select the year
        min: 2000
        max: 2100
        value: 2022
    some_text:
        output: markdown
        value: |
    
            ## Header 2

            This is **markdown**

            - mulitline
            - amama
            
            Link to [mljar](https://mljar.com)
```
