### ISSUE TITLE
add themes to slides

### ISSUE THREAD

**Issue by pplonski** [mljar/mercury#90]

**Comment by pplonski** [comment]
You can check slides themes in [the app](https://slides-themes.herokuapp.com/).

#### Light themes:

- white (default)
- sky
- beige
- simple
- serif
- solarized

#### Dark themes: 

- black
- league
- blood
- night
- moon

To use the theme in the Mercury YAML configuration you need to define `format`. The example below:

```yaml
title: My app
output: slides
format:
    theme: night
# the rest of YAML ...
```

Please check the [docs](https://mercury-docs.readthedocs.io/en/latest/interactive-slides/) for more information.

### Themes gallery

The app is deployed at [Heroku](https://slides-themes.herokuapp.com/).

![](https://github.com/mljar/mercury-slides-themes/raw/main/media/slides-themes-list.gif)
