### ISSUE TITLE
Send information about scheduled notebooks by email

### ISSUE THREAD

**Issue by pplonski** [mljar/mercury#99]
Please add an option to send email about scheduled notebook. Consider the following options:
- email when execution failed
- email when execution succeded
- email notebook in the attachment as HTML
- email notebook in the attachment as PDF

Other ideas?

**Comment by pplonski** [comment]
There will be new parameter `notify`. The example usage:

```
notify:
    on_success: email1, email2, username1
    on_failure: email1, username2
    attachment: html, pdf
```

You will be able to decide who will be notified about successful execution and failure execution. There will be an option `attachment` to send in the email HTML or PDF with executed notebook.
